# Generated by Django 5.1 on 2024-09-01 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_chapter_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='readingmark',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reading_marks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='readingmark',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_marks', to='books.chapter'),
        ),
    ]
